server:
  port: 8081

spring:
  application:
    name: user-ms

  datasource:
    url: jdbc:postgresql://user-db:5432/userdb
    driverClassName: org.postgresql.Driver
    username: user_user
    password: user_pass

  jpa:
    hibernate:
      ddl-auto: update   # Para desarrollo (en prod usa validate o none)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    jpa:
      repositories:
        enabled: true

# Configuraci贸n de JWT
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # Clave secreta para firmar JWT (en producci贸n usar variable de entorno)
  expiration: 86400000 # 24 horas en milisegundos

# Configuraci贸n de microservicios
microservices:
  auth-service:
    url: http://auth-ms:8079

# Configuraci贸n de logging
logging:
  level:
    com.microservices: DEBUG
    com.microservices.service.AuthorizationService: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8091/eureka/
