server:
  port: 8079

spring:
  application:
    name: auth-ms

# Configuración de JWT
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 horas en milisegundos


# Configuración de logging
logging:
  level:
    com.microservices.auth: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.openfeign: DEBUG
